### ISSUE TITLE
Proposal: supporting multiple structures

### ISSUE THREAD

**Issue by themisir** [thisisyusub/kanza-cli#4]
### Description:

The cli currently creates project using predefined / hardcoded structure. I think it could be expanded even more to support creating projects using multiple templates.

The templates could be stored and retrieved from git source and you'll just need to clone the template git repo to a temporary folder and copy contents inside the directory to project dir. I wouldn't suggest cloning it to project directory cause it might cause conflicts with the project version tracking / control.

Doing so will let users to:

- Create personal templates
- Fork & customize exists templates
- Make it easy to maintain template contents than hard coding into the project

That's just my thoughts on that, looking forward to your thoughts. What do you think about that?

**Comment by thisisyusub** [comment]
Thanks for your feedback! This is the good cases to care about. I will try to implement something related to it 👍🏻
