### ISSUE TITLE
Folder File Structure Enhancement Proposal

### ISSUE THREAD

**Issue by theamiri** [thisisyusub/kanza-cli#5]

**Comment by thisisyusub** [comment]
Our structure is similar to it I think. Just a difference is that, you just have only one global `core` directory to store all globals, utils and etc. In our structure:

- `ui (presentation)/core` folder is used to store ui related constants, utilities and etc.
- `bloc/core` folder is used to store bloc related things 
- and `data/core` for data related things
- `utils` is used to store global utilities or something else (maybe mixins, extensions and etc)

Why it needs enhance? Can you please, give detailed information?
